import mongoose from "mongoose";

const userschema = mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true },
  phone: { type: String },
  password: { type: String, required: true },
  about: { type: String },
  tags: { type: [String] },
  emailNotifications: { type: Boolean, default: true },
  smsNotifications: { type: Boolean, default: false },
  joinDate: { type: Date, default: Date.now },
  role: { type: String, enum: ["user", "admin"], default: "user" },
  following: [{ type: mongoose.Schema.Types.ObjectId, ref: "user" }],
  followers: [{ type: mongoose.Schema.Types.ObjectId, ref: "user" }],
  isSuspended: { type: Boolean, default: false },
  suspendedUntil: { type: Date },
  violationCount: { type: Number, default: 0 },
  lastForgotPasswordRequest: { type: Date },
  plan: { type: String, enum: ["free", "bronze", "silver", "gold"], default: "free" },
  subscriptionStatus: { type: String, enum: ["active", "expired", "inactive"], default: "active" },
  subscriptionStartDate: { type: Date, default: Date.now },
  subscriptionEndDate: { type: Date },
  billingName: { type: String },
  billingEmail: { type: String },
  billingAddress: { type: String },
  reputation: { type: Number, default: 0 },
  profileCompletionBonusAwarded: { type: Boolean, default: false },
  language: { type: String, enum: ["en", "es", "hi", "pt", "zh", "fr"], default: "en" },
  languageOTP: { type: String },
  languageOTPExpiry: { type: Date },
  pendingLanguage: { type: String },
});
export default mongoose.model("user", userschema);
